---
output: 
    github_document:
        includes: 
            in_header: ../render/header.html
            before_body: ../render/menu.html
---

## Philosophy

Just pull big points from my philosophy and talk about reaching groups.  


## Courses 

Teaching has always been a passion of mine. I am privileged to have taught both undergraduate and graduate courses, including many courses for our online Master's program. The courses I've taught at NCSU are listed below.  The courses I've designed and created are in bold.

- **ST 307 - Introduction to Statistical Programming - SAS**
- **ST 308 - Introduction to Statistical Programming - R**
- ST 311 - Introduction to Statistics
- ST 370 - Probability and Statistics for Engineers
- ST 372 - Introduction to Statistical Inference and Regression
- ST 421 - Introduction to Mathematical Statistics I
- ST 422 - Introduction to Mathematical Statistics II
- **ST 501 - Fundamentals of Inference I**
- **ST 502 - Fundamentals of Inference II**
- ST 511 - Statistical Methods For Researchers I
- ST 512 - Statistical Methods For Researchers II
- **ST 513 - Statistics for Management and Social Sciences I**
- ST 521 - Statistical Theory I
- ST 555 - Statistical Programming I
- **ST 558 - Introduction to Data Science**

If you are currently enrolled in one of these courses, the material for the classes is available on <wolfware.ncsu.edu>.

