---
output: 
    github_document:
        includes: 
            in_header: ../render/header.html
            before_body: ../render/menu.html
---


## Basics of R  

As part of my efforts to prepare our Online Master of Statistics and Applied Statistics and Data Management Certificate students, I  developed this short course on learning to use the R software.  

The course was a free, open, non-credit course and is meant to provide training to our current graduate students on the basics of R so that learning how to use R doesn’t hinder their learning in the courses that use R in our programs.

## Course Goals

This course is designed to demonstrate the basic use of R for reading, manipulating, and plotting data via RStudio.  By the end of this course students will be able to:  

- read and write basic R programs
- import well-formatted raw data into R using the `tidyverse`
- complete common data manipulation tasks in R using the `tidyverse`
- produce numerical and graphical summaries in R in `baseR` and the `tidyverse`  

Although the course is no longer available, the video lectures from the course (no access to the code, assignments, etc.) can be found on this <a href = "https://bit.ly/R-playlist" target = "_blank">course video at this playlist</a>.  


## Online Statistics Programs @ NC State  

Want to join our online community?  <a href = "https://statistics.sciences.ncsu.edu/graduate/online-programs/" target ="_blank">Check here for more information about our Online Master of Statistics and Online Graduate Certificate programs.</a>