---
output: 
    github_document:
        includes: 
            in_header: ../render/header.html
            before_body: ../render/menu.html
---


## Undergrad Research (UR)

For three years I led the departmental efforts to improve access to research for undergraduate students.
Students involved in UR gain sought after critical thinking skills and often form a deeper connection with the department (this being very important as our department's undergraduate program has grown a ton over the past 15 years).

However, there are barriers for undergraduate students contemplating doing research. Many don't know what research is like, where to find projects, or even that these kinds of opportunities are available. On the faculty side, there can be hesitation to working with undergraduates as it can be difficult to have collaborations that end successfully.

My goals as the Director of Undergraduate Research were:

- to make UR opportunities an essential part of the curriculum
- provide a centralized place for students to get information about opportunities and see past examples of projects
- promote/create new opportunities for students to get involved
- facilitate success for both the students and faculty mentors

Providing clear expectations about the projects really helped the students and faculty. ([See here for an example blank contract.](files/UndergradResearchFiles/ProjectSyllabus.docx)) We required that each project should (almost always) include the following:

- the use of software
- a striking visual demonstration (graph or video) to highlight the important question and result under consideration
- real-data analysis
- communication in both oral and written forms

We created a research cohort across the department that included (all required):

- weekly working meetings with me (and Jonathan Duggins) where we would provide general support
    + This proved effective in preventing the students from hitting a simple roadblock and getting stuck (which often would lead to ineffective meetings with their faculty advisors)
- low stakes discussions among the cohort (with free pizza) each month
    + This was highly effective. It was really amazing to see the students grow from their first sessions where they often struggled to articulate what they were even trying to do to the end when they had a solid elevator speech to both the lay and statistical audience.  
- filling out [a weekly progress form](files/UndergradResearchFiles/MeetingProgressForm.docx) with their advisor at each meeting

I organized a session around [undergraduate research as JSM 2018](https://ww2.amstat.org/meetings/jsm/2018/onlineprogram/ActivityDetails.cfm?SessionID=215256) ([slides available here](files/UndergradResearchFiles/Post_Justin_Implementing_a_Department-wide_Undergraduate_Research_Program_153.pdf)). Unfortunately, with a change in leadership the role disappeared when I moved to being Director of Online Education. I still have lots of thoughts about UR at a departmental level. If you want to chat about it, please reach out!

The [Council on undergraduate research](https://www.cur.org/) has a lot of great resources.


## Statistical Learning Group

For a few years I had the pleasure of being the faculty mentor to the statistical learning group (SLG).  The group was originally formed by [Jami Jackson](https://www.linkedin.com/in/jami-mulgrave-ph-d-3419445/), [Neal Grantham](https://www.linkedin.com/in/nsgrantham/), [Joshua Day](https://www.linkedin.com/in/joshday/), [Dendi Suhubdy](https://www.linkedin.com/in/dendisuhubdy/), and [Brian Gaines](https://www.linkedin.com/in/briangainesstats/). Later Todd Wilson and [Kara Martinez](https://www.linkedin.com/in/kara-martinez-1163a4152/) led the group. All awesome people!

The group had four major goals:

- Introduce advanced topics in data mining, machine learning, and other 'active' areas of statistics in order to broaden the students' knowledge base and, where possible, connect statistical ideas. 
    + With the "Data Science" revolution, these methods became very important to have an understanding of
- Offer opportunities to present upper level topics and improve presentation and teaching ability with a focus on audience of the presentation and data visualizations.
    + Provide presenting students 'mentors' to help them effectively present.
- Give outlets for presentation, writing, and computing that are available for prospective employers to view.
    + Many of the presentations were recorded and made available.
    + Write-ups and code were made available when possible as well.
- Improve applied analysis skills and coding.
    + Presentations included an analysis or simulation aspect with code available for all members to work through when possible.

As our curriculum caught up, the need for the group diminished (and I had my first child :). The group did have a brief resurgence just prior to the pandemic.  [Jimmy Hickey](https://www.linkedin.com/in/jimmyjhickey/) and [Alvin Sheng](https://www.linkedin.com/in/alvin-sheng-b06351110/) led a reading group for the book [Deep Learning with R](https://github.com/AlvinSheng/SLG-Deep-Learning). 

If you are interested, I'm placed some of the [presentations here](SLGpresentations.html).



<!--

## NC State workshops and slides here

## Articles from FF, etc.



# Sports Stats



# Executive Ed Teaching



# Outreach & Diversity

## Stat'n'Chat

The Stat'n'Chat group is a collection of some local introductory statistics instructors from different high schools/colleges/universities that have gotten together to network and share ideas. We've had people from NC State, Wake Tech Community College, Meredith College, Cary Academy, and a few others.

We usually meet monthly on Friday for dinner and discussion.  If you are interested in joining, please e-mail me and I'll add you to our mailing list!

## High School Collaboration

Met Craig Lazarski and Kristi Ramey @ cary academy

## Juntos

Juntos is a program that NC State started in 2007 to 'provide high school Latino students and their families with the knowledge, skills, and resources to ensure high school graduate and increase college access and attendance rates.'

I got started with the group in 2017 when one of our undergraduate students did a project with them. After meeting with them, we decided to have an undergraduate internship/research type position there for a few semesters. During this time I helped them to completely revamp their data collection and reporting processes (we went from individual excel files and manually tabulation to a database with an online form their mentors could use with automated reporting). Our student [Didier Turcios](https://www.linkedin.com/in/didierturcios/) held the internship position there for a year and now serves as their program evaluator! (He's also a current statistician at RTI International and in our online master's of statistics program.)

This is a really fantastic program and I'm happy to have been involved!

## Cary PD

In 2017 I advised [Grant Swigart](https://www.linkedin.com/in/grantswigart/) on a really interesting project with the Cary Police Department. The goal was:

> To utilize a neutral, third party subject matter expert (NCSU Statistics) to proactively analyze Cary PD’s traffic stops on both an aggregate and individual level and determine if we have any statistically significant deviations from a normal range as it relates to officer traffic stops, searches, and arrests of women, persons of color and Hispanic heritage.  Our benchmark/point of comparison will be the gender, race, and heritage of persons involved in traffic collisions as captured by Cary PD’s traffic collision reports.  These data are much more representative of who makes up the motoring public than census data, which is designed purely to captures residency information. Statistical deviations from the norm in and of themselves will not to be considered indicative of wrongdoing, but rather will serve as an impetus to further examine the circumstances involved with the officer or group of officers outside the normal range.

Grant did a great job working through the data and literature (he ultimately went on to get a master's degree in statistics from NC State). Ultimately we stopped hearing back from the Cary PD after our initial findings of some differences in traffic stop distributions.


## GLBT advocate

> The GLBT Advocate Program is intended to be a continuing education and engagement program for NC State faculty and staff. The Program is designed to provide faculty and staff with ongoing opportunities for learning and for showing their support as Allies and Advocates of the GLBT community. Faculty and staff who would like to participate in the Program agree to complete one educational workshop and attend one GLBT event on campus each year. 

I've enjoyed being a [GLBT advocate](https://diversity.ncsu.edu/glbt/glbt-advocate-list/
) since 2017. The program is really educational and has helped me to understand barriers and issues faced by those in the GLBT community.

## Pack Promise Mentor

[Pack Promise](https://news.ncsu.edu/tag/pack-promise/) is a great program for families with limited financial resources. Students from these families tend to be first-generation college students. As a first generation college student myself, I was really glad to see NC State has a program to help guide students through the unknowns of a large university. I served as a Pack Promise faculty mentor to a stats major (she now has a master's degree in statistics!). We met each semester to talk about clubs to get involved with, opportunities within the department and campus, and generally answered any questions about how things work at the university. All things I wish I had when I was an undergraduate student! (I never even considered graduate school until my senior year of college!)  


-->